config/routes.rb
Rails.application.routes.draw do

  # this creates /optimizer
  get 'optimizer', to: 'pages#optimizer'
  get 'optimizer/results', to: 'pages#outcome', as: 'optimizer_results'

  post 'optimizer/results', to: 'pages#submit', as: 'submit_data'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def optimizer

  end

  def submit
    @data1 = params[:data1]
    @data2 = params[:data2]
    redirect_to optimizer_results_path(data1: @data1, data2: @data2)
  end

  def outcome

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RouteOptimizer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/optimizer.html.erb
<h1>Optimizer</h1>

<%= form_tag(submit_data_path, method: :post) do %>
  <div>
    <%= label_tag :data1, "Data 1:" %>
    <%= text_field_tag :data1 %>
  </div>

  <div>
    <%= label_tag :data2, "Data 2:" %>
    <%= text_field_tag :data2 %>
  </div>

  <%= submit_tag "Submit" %>
<% end %>

app/views/pages/outcome.html.erb
<h1>What is your outcome?</h1>
<p><%= params[:data1] %></p>
<p><%= params[:data2] %></p>